export const CHANGE_IS_LOADING = "CHANGE_IS_LOADING";
export const ADD_LOADED_MOVIES = "ADD_LOADED_MOVIES";
export const ADD_NEW_LIKED_MOVIE = "ADD_NEW_LIKED_MOVIE";
export const REMOVE_LIKED_MOVIE = "REMOVE_LIKED_MOVIE";
export const ADD_NEW_USER_MOVIE = "ADD_NEW_USER_MOVIE";
export const REMOVE_USER_MOVIE = "REMOVE_USER_MOVIE";
export const CHANGE_TEMP_NEW_MOVIE_PROP = "CHANGE_TEMP_NEW_MOVIE_PROP";
export const RESET_TEMP_NEW_MOVIE = "RESET_TEMP_NEW_MOVIE";
